"""initial_schema

Revision ID: fc45e3945456
Revises:
Create Date: 2026-06-13 15:00:48.259426
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'fc45e3945456'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _is_postgresql() -> bool:
    """Check if the current database dialect is PostgreSQL."""
    bind = op.get_bind()
    return bind.dialect.name == "postgresql"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if _is_postgresql():
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('auth_provider', sa.String(length=20), nullable=False),
    sa.Column('auth_provider_id', sa.String(length=255), nullable=False),
    sa.Column('tfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('tfa_secret', sa.String(length=255), nullable=True),
    sa.Column('preferencias_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_provider', 'auth_provider_id', name='uq_auth_provider')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('categorias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('icono', sa.String(length=10), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('es_predefinida', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('palabras_clave', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categorias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metas_ahorro',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('monto_objetivo', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('monto_acumulado', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fecha_deseada', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notificaciones_usuario_leida', 'notificaciones', ['usuario_id', 'leida'], unique=False)
    op.create_table('sesiones_chat',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarjetas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('banco', sa.String(length=100), nullable=False),
    sa.Column('ultimos_4_digitos', sa.String(length=4), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extractos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tarjeta_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('periodo_inicio', sa.Date(), nullable=True),
    sa.Column('periodo_fin', sa.Date(), nullable=True),
    sa.Column('fecha_corte', sa.Date(), nullable=True),
    sa.Column('fecha_limite_pago', sa.Date(), nullable=True),
    sa.Column('pago_minimo', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('pago_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cupo_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cupo_disponible', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tasas_interes_json', sa.JSON(), nullable=True),
    sa.Column('metadatos_json', sa.JSON(), nullable=True),
    sa.Column('archivo_s3_key', sa.String(length=1024), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tarjeta_id'], ['tarjetas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tarjeta_id', 'periodo_inicio', 'periodo_fin', name='uq_extracto_tarjeta_periodo')
    )
    op.create_index('ix_extractos_tarjeta_fecha', 'extractos', ['tarjeta_id', 'periodo_inicio'], unique=False)
    op.create_index('ix_extractos_usuario_estado', 'extractos', ['usuario_id', 'estado'], unique=False)
    op.create_table('mensajes_chat',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sesion_id', sa.UUID(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('tokens_usados', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_chat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presupuestos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=False),
    sa.Column('limite_mensual', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('alerta_80pct', sa.Boolean(), nullable=False),
    sa.Column('alerta_100pct', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('limite_mensual > 0', name='ck_limite_positivo'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'categoria_id', name='uq_presupuesto_usuario_categoria')
    )
    op.create_table('traducciones_comercios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_original', sa.String(length=500), nullable=False),
    sa.Column('nombre_traducido', sa.String(length=500), nullable=False),
    sa.Column('categoria_sugerida_id', sa.UUID(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('votos', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_sugerida_id'], ['categorias.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traducciones_comercios_nombre_original'), 'traducciones_comercios', ['nombre_original'], unique=False)
    op.create_table('transacciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('extracto_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('numero_autorizacion', sa.String(length=100), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('comercio_original', sa.String(length=500), nullable=False),
    sa.Column('comercio_traducido', sa.String(length=500), nullable=True),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('numero_cuotas', sa.String(length=20), nullable=True),
    sa.Column('cuotas_totales', sa.Integer(), nullable=True),
    sa.Column('cuota_actual', sa.Integer(), nullable=True),
    sa.Column('valor_cuota', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('interes_mensual_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('interes_anual_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('saldo_pendiente', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('moneda_original', sa.String(length=10), nullable=True),
    sa.Column('valor_moneda_original', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('es_abono', sa.Boolean(), nullable=False),
    sa.Column('es_cuota', sa.Boolean(), nullable=False),
    sa.Column('parent_transaccion_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['extracto_id'], ['extractos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_transaccion_id'], ['transacciones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    if _is_postgresql():
        op.create_index('ix_transacciones_busqueda', 'transacciones', ['comercio_original'], unique=False, postgresql_using='gin', postgresql_ops={'comercio_original': 'gin_trgm_ops'})
    op.create_index('ix_transacciones_categoria', 'transacciones', ['categoria_id'], unique=False)
    op.create_index('ix_transacciones_comercio', 'transacciones', ['comercio_original'], unique=False)
    op.create_index('ix_transacciones_extracto', 'transacciones', ['extracto_id'], unique=False)
    op.create_index(op.f('ix_transacciones_fecha'), 'transacciones', ['fecha'], unique=False)
    op.create_index('ix_transacciones_usuario_fecha', 'transacciones', ['usuario_id', 'fecha'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('token_jti', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_jti')
    )
    op.create_index('ix_refresh_tokens_usuario', 'refresh_tokens', ['usuario_id'], unique=False)
    op.create_index('ix_refresh_tokens_jti', 'refresh_tokens', ['token_jti'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transacciones_usuario_fecha', table_name='transacciones')
    op.drop_index(op.f('ix_transacciones_fecha'), table_name='transacciones')
    op.drop_index('ix_transacciones_extracto', table_name='transacciones')
    op.drop_index('ix_transacciones_comercio', table_name='transacciones')
    op.drop_index('ix_transacciones_categoria', table_name='transacciones')
    if _is_postgresql():
        op.drop_index('ix_transacciones_busqueda', table_name='transacciones', postgresql_using='gin', postgresql_ops={'comercio_original': 'gin_trgm_ops'})
    op.drop_table('transacciones')
    op.drop_index(op.f('ix_traducciones_comercios_nombre_original'), table_name='traducciones_comercios')
    op.drop_table('traducciones_comercios')
    op.drop_table('presupuestos')
    op.drop_table('mensajes_chat')
    op.drop_index('ix_extractos_usuario_estado', table_name='extractos')
    op.drop_index('ix_extractos_tarjeta_fecha', table_name='extractos')
    op.drop_table('extractos')
    op.drop_table('tarjetas')
    op.drop_table('sesiones_chat')
    op.drop_index('ix_notificaciones_usuario_leida', table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_table('metas_ahorro')
    op.drop_table('categorias')
    op.drop_index('ix_refresh_tokens_jti', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_usuario', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
